## SECTION 01 결측치 처리

In [2]:
import pandas as pd
url = 'https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'
titanic_df = pd.read_csv(url, sep='\t')
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    str
 4   Sex          156 non-null    str
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    str
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     str
 11  Embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [3]:
# 모든 열을 소문자로 변경

new_columns=['passengerId', 'servived', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare', 'cabin', 'embarked']
titanic_df.columns = new_columns
titanic_df.columns

Index(['passengerId', 'servived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='str')

### 결측치 확인 함수

In [4]:
# isna 함수

titanic_df['age'][titanic_df['age'].isna()]

5     NaN
17    NaN
19    NaN
26    NaN
28    NaN
29    NaN
31    NaN
32    NaN
36    NaN
42    NaN
45    NaN
46    NaN
47    NaN
48    NaN
55    NaN
64    NaN
65    NaN
76    NaN
77    NaN
82    NaN
87    NaN
95    NaN
101   NaN
107   NaN
109   NaN
121   NaN
126   NaN
128   NaN
140   NaN
154   NaN
Name: age, dtype: float64

In [5]:
# isnull 함수

titanic_df['age'].isnull()
titanic_df['age'][titanic_df['age'].isnull()]
titanic_df['age'][titanic_df['age'].isnull()].isnull().sum()

np.int64(30)

In [6]:
# notnull 함수

titanic_df['age'].notnull()
titanic_df['age'][titanic_df['age'].notnull()]
titanic_df.loc[titanic_df['age'].notnull(), ['age', 'name']]
titanic_df.loc[titanic_df['age'].isnull(), ['age','name']]

     age                                            name
5    NaN                                Moran, Mr. James
17   NaN                    Williams, Mr. Charles Eugene
19   NaN                         Masselmani, Mrs. Fatima
26   NaN                         Emir, Mr. Farred Chehab
28   NaN                   O'Dwyer, Miss. Ellen "Nellie"
29   NaN                             Todoroff, Mr. Lalio
31   NaN  Spencer, Mrs. William Augustus (Marie Eugenie)
32   NaN                        Glynn, Miss. Mary Agatha
36   NaN                                Mamee, Mr. Hanna
42   NaN                             Kraeff, Mr. Theodor
45   NaN                        Rogers, Mr. William John
46   NaN                               Lennon, Mr. Denis
47   NaN                       O'Driscoll, Miss. Bridget
48   NaN                             Samaan, Mr. Youssef
55   NaN                               Woolner, Mr. Hugh
64   NaN                           Stewart, Mr. Albert A
65   NaN                        Moubarek, Master. Gerios
76   NaN                               Staneff, Mr. Ivan
77   NaN                        Moutal, Mr. Rahamin Haim
82   NaN                  McDermott, Miss. Brigdet Delia
87   NaN                   Slocovski, Mr. Selman Francis
95   NaN                     Shorney, Mr. Charles Joseph
101  NaN                Petroff, Mr. Pastcho ("Pentcho")
107  NaN                          Moss, Mr. Albert Johan
109  NaN                             Moran, Miss. Bertha
121  NaN                      Moore, Mr. Leonard Charles
126  NaN                             McMahon, Mr. Martin
128  NaN                               Peter, Miss. Anna
140  NaN                   Boulos, Mrs. Joseph (Sultana)
154  NaN                           Olsen, Mr. Ole Martin

### 결측치 처리방법

In [7]:
# 결측치를 다른 문자로 변경하기

titanic_df.head()
titanic_df['cabin']=titanic_df['cabin'].fillna('N')
titanic_df['cabin']

titanic_df['cabin'].value_counts()
titanic_df['cabin'][0]

titanic_df['cabin']=titanic_df['cabin'].apply(lambda x: x[0])
titanic_df['cabin']
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   passengerId  156 non-null    int64
 1   servived     156 non-null    int64
 2   pclass       156 non-null    int64
 3   name         156 non-null    str
 4   sex          156 non-null    str
 5   age          126 non-null    float64
 6   sibsp        156 non-null    int64
 7   parch        156 non-null    int64
 8   ticket       156 non-null    str
 9   fare         156 non-null    float64
 10  cabin        156 non-null    str
 11  embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [8]:
# 결측치를 평균값으로 변경하기

titanic_df_copy = titanic_df.copy()
titanic_df_copy

,passengerId,servived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,N,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,N,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,N,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,N,C

In [9]:
titanic_df_copy['age'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
151    False
152    False
153    False
154     True
155    False
Name: age, Length: 156, dtype: bool

In [10]:
titanic_df_copy['age'] = titanic_df_copy['age'].fillna(titanic_df_copy['age'].mean())
titanic_df_copy['age']

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
151    22.000000
152    55.500000
153    40.500000
154    28.141508
155    51.000000
Name: age, Length: 156, dtype: float64

In [11]:
# 데이터프레임 복사 - 얕은 복사와 깊은 복사

copy_titanic_df = titanic_df.copy()
copy_titanic_df

,passengerId,servived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,N,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,N,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,N,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,N,C

In [12]:
# hex함수를 이용해 원본과 복사된 데이터프레임의 주소를 확인

hex(id(titanic_df))

'0x20beb2382b0'

In [13]:
hex(id(copy_titanic_df))

'0x20beb2424d0'

In [14]:
# head함수를 이용해 원본인 titanic_df와 복사본인 copy_titanic_df의 내용을 확인

titanic_df.head()

,passengerId,servived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S

In [15]:
copy_titanic_df.head()

,passengerId,servived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S

In [16]:
# copy_titanic_df의 age열을 모두 0으로 변경하고 head 함수로 확인

copy_titanic_df['age'] = 0
copy_titanic_df.head()

,passengerId,servived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,0,0,0,373450,8.0500,N,S

In [17]:
# copy함수로 복사면 원본데이터프레임의 값이 변경되지 않는 것을 확인 >> ㄷㅏ른 주소값이라서

titanic_df.head()

,passengerId,servived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,N,S

## SECTION 03 판다스의 통계 함수

In [18]:
# 데이터의 통계치 확인하기

titanic_df.describe()

,passengerId,servived,pclass,age,sibsp,parch,fare
count,156.000000,156.000000,156.000000,126.000000,156.000000,156.000000,156.000000
mean,78.500000,0.346154,2.423077,28.141508,0.615385,0.397436,28.109587
std,45.177428,0.477275,0.795459,14.613880,1.056235,0.870146,39.401047
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000
25%,39.750000,0.000000,2.000000,19.000000,0.000000,0.000000,8.003150
50%,78.500000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200
75%,117.250000,1.000000,3.000000,35.000000,1.000000,0.000000,30.371850
max,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000

In [19]:
# 합계 구하기

titanic_df.sum()

passengerId                                                12246
servived                                                      54
pclass                                                       378
name           Braund, Mr. Owen HarrisCumings, Mrs. John Brad...
sex            malefemalefemalefemalemalemalemalemalefemalefe...
age                                                      3545.83
sibsp                                                         96
parch                                                         62
ticket         A/5 21171PC 17599STON/O2. 31012821138033734503...
fare                                                   4385.0956
cabin          NCNCNNENNNGCNNNNNNNNNDNANNNCNNNBNNNNNNNNNNNNNN...
embarked       SCSSSQSSSCSSSSSSQSSCSSQSSSCSQSCCQSCSCSSCSSCCQS...
dtype: object

In [20]:
# 총 개수 구하기

titanic_df.count()

passengerId    156
servived       156
pclass         156
name           156
sex            156
age            126
sibsp          156
parch          156
ticket         156
fare           156
cabin          156
embarked       155
dtype: int64

In [21]:
# 최댓값 구하기

titanic_df.max()

passengerId                                156
servived                                     1
pclass                                       3
name           van Billiard, Mr. Austin Blyler
sex                                       male
age                                       71.0
sibsp                                        5
parch                                        5
ticket                             W.E.P. 5734
fare                                     263.0
cabin                                        N
embarked                                     S
dtype: object

In [22]:
#  최솟값 구하기

titanic_df.min()

passengerId                                                 1
servived                                                    0
pclass                                                      1
name           Ahlin, Mrs. Johan (Johanna Persdotter Larsson)
sex                                                    female
age                                                      0.83
sibsp                                                       0
parch                                                       0
ticket                                                 110465
fare                                                     6.75
cabin                                                       A
embarked                                                    C
dtype: object

In [23]:
# 평균값 구하기

titanic_df.mean(numeric_only=True)

passengerId    78.500000
servived        0.346154
pclass          2.423077
age            28.141508
sibsp           0.615385
parch           0.397436
fare           28.109587
dtype: float64

In [24]:
# 중간값 구하기

titanic_df.median(numeric_only=True)

passengerId    78.5000
servived        0.0000
pclass          3.0000
age            26.0000
sibsp           0.0000
parch           0.0000
fare           14.4542
dtype: float64

In [25]:
# 최빈값 구하기

titanic_df.mode()

,passengerId,servived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0.0,3.0,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",male,21.0,0.0,0.0,113803,8.05,N,S
1,2,NaN,NaN,"Allen, Mr. William Henry",NaN,NaN,NaN,NaN,11668,NaN,NaN,NaN
2,3,NaN,NaN,"Andersson, Miss. Ellis Anna Maria",NaN,NaN,NaN,NaN,19950,NaN,NaN,NaN
3,4,NaN,NaN,"Andersson, Miss. Erna Alexandra",NaN,NaN,NaN,NaN,237736,NaN,NaN,NaN
4,5,NaN,NaN,"Andersson, Mr. Anders Johan",NaN,NaN,NaN,NaN,2651,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,NaN,NaN,"Williams, Mr. Charles Duane",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,153,NaN,NaN,"Williams, Mr. Charles Eugene",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,154,NaN,NaN,"Woolner, Mr. Hugh",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,155,NaN,NaN,"Zabour, Miss. Hileni",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,156,NaN,NaN,"van Billiard, Mr. Austin Blyler",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
# 편차 구하기

num_df = titanic_df.select_dtypes(include='number')

(num_df - num_df.mean()).abs().mean()

passengerId    39.000000
servived        0.452663
pclass          0.710059
age            11.142858
sibsp           0.773176
parch           0.616535
fare           22.619713
dtype: float64

In [27]:
# 분산 구하기

titanic_df.var(numeric_only=True)

passengerId    2041.000000
servived          0.227792
pclass            0.632754
age             213.565487
sibsp             1.115633
parch             0.757155
fare           1552.442481
dtype: float64

In [28]:
# 표준편차 구하기

titanic_df.std(numeric_only=True)

passengerId    45.177428
servived        0.477275
pclass          0.795459
age            14.613880
sibsp           1.056235
parch           0.870146
fare           39.401047
dtype: float64

In [31]:
# 왜도 구하기

titanic_df.skew(numeric_only=True)

passengerId    0.000000
servived       0.653058
pclass        -0.912744
age            0.700367
sibsp          2.220685
parch          2.760421
fare           4.176408
dtype: float64

In [30]:
# 첨도 구하기

titanic_df.kurt(numeric_only=True)

passengerId    -1.200000
servived       -1.594120
pclass         -0.803872
age             0.613747
sibsp           4.996881
parch           9.346662
fare           21.109985
dtype: float64

In [ ]:
# 측정 열의 통계치 구하기

titanic_df['age'].max()

np.float64(71.0)

In [ ]:
titanic_df['age'].min()

np.float64(0.83)

In [ ]:
titanic_df['age'].sum()

np.float64(3545.83)

In [ ]:
titanic_df['age'].count()

np.int64(126)

In [ ]:
titanic_df['age'].mean()

np.float64(28.141507936507935)

In [ ]:
titanic_df['age'].sum()/titanic_df['age'].count()

np.float64(28.141507936507935)

In [ ]:
titanic_df['age'].std()

np.float64(14.613879926560793)

In [ ]:
titanic_df['age'].median()

np.float64(26.0)

In [ ]:
titanic_df['age'].mode()

0    21.0
Name: age, dtype: float64