## 1. 파이썬 파일 처리

In [ ]:
sample_file = 'data/sample.txt'

In [ ]:
# 파일을 open하여 전체 내용을 읽어서 출력
with open(sample_file, mode='rt', encoding='utf-8') as f:
    content = f.read()
    print(content)
print("----- 끝 -----")

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

----- 끝 -----

In [ ]:
# 파일을 open하고 한 줄씩 읽어서 출력하기
with open(sample_file, 'r', encoding='utf-8') as f:
    lines = f.readlines()
    for line in lines:
        print(line, end="")
print("----- 끝 -----")

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.
----- 끝 -----

In [ ]:
with open(sample_file, 'r', encoding='utf-8') as f:
    line = f.readline()
    while line:
        print(line, end="")
        line = f.readline()

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.

In [ ]:
# 파일객체에서 한 줄씩 읽어 오기
# 파일 객체 f를 반복문에서 사용하면 파일을 한 줄씩 읽으며,
# 각 줄 끝의 \n도 포함해서 가져옵
with open(sample_file, 'r', encoding='utf-8') as f:
    for line in f:
        print(line, end='')

print("----- 끝 -----")

나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.
----- 끝 -----

In [ ]:
# 여러 개의 파일 읽기 (모든 txt 파일을 읽어서 출력하기)
import glob
txt_file_pattern = "data/*.txt"
files = glob.glob(txt_file_pattern)
print(files)

for file in files:
    print(file)

    with open(file, mode = 'r', encoding='utf-8') as f:
            line = f.read()
            print(line, end='')

print("----- 끝 -----")

['data\\hello.txt', 'data\\sample.txt', 'data\\score.txt']
data\hello.txt
안녕하세요
hello
내용을 추가합니다.
저장하는 문서 이름,  'w' 대신 'a'를 사용합니다.
data\sample.txt
나의 속도로

조금 늦어도 괜찮다.
남들과 같은 길을 갈 필요도 없다.

오늘 배운 것 하나,
오늘 해결한 문제 하나가
조금씩 나의 실력이 된다.

결과가 보이지 않는 날에도
나는 앞으로 가고 있다.

빠르게 가는 것보다
멈추지 않는 것이 중요하다.

오늘의 작은 한 걸음이
내일의 나를 만든다.

나는 늦은 것이 아니라
나의 속도로 가고 있다.
data\score.txt
90
100
85
95----- 끝 -----

## 2. 파이썬 문자열 다루기

In [ ]:
# 양쪽 공백 제거
b1=" 작은 일에 성실한 사람은      큰일에도 성실하고 "
b1.strip()

'작은 일에 성실한 사람은      큰일에도 성실하고'

In [ ]:
# 왼쪽 문자, 오른쪽 문자, 양쪽 문자 제거
text="....작은 일에 성실한 사람은, 큰일에도 성실하고...."
text = text.rstrip('.')
text

'....작은 일에 성실한 사람은, 큰일에도 성실하고'

In [ ]:
# ,로 문자열 분리
text="....작은 일에 성실한 사람은, 큰일에도 성실하고...."
print(text.split())
print(text.split(','))

['....작은', '일에', '성실한', '사람은,', '큰일에도', '성실하고....']
['....작은 일에 성실한 사람은', ' 큰일에도 성실하고....']

In [ ]:
# .으로 문자열 분리
numbers="1. 2. 3. 4. 5. 6"
numbers.split(".")

['1', ' 2', ' 3', ' 4', ' 5', ' 6']

## 3. 판다스로 데이터 가져오기

In [ ]:
# 판다스 설치
!pip install pandas

Requirement already satisfied: pandas in C:\Users\user\anaconda3\envs\pydata26\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\user\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\user\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\user\anaconda3\envs\pydata26\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\user\anaconda3\envs\pydata26\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
# 연습용 sample_data.csv 로딩하기
sample_file = 'data/sample_data.csv'

import pandas as pd
sample_df = pd.read_csv(sample_file)
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [ ]:
sample_df.to_csv('data/sample_data_copy.csv', index=False)

In [ ]:
df2 = pd.read_csv('data/sample_data_copy.csv', index_col = 'Name')
df2

          Age Gender         City
Name
Alice    24.0      F     New York
Bob       NaN      M  Los Angeles
Charlie  22.0      M          NaN
David    29.0      M      Chicago
Edward    NaN      M      Houston
Alice    24.0      F     New York
Susan    32.0      F      Houston

In [ ]:
# 타이타닉 데이터 가져오기
titanic_data = 'https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'

In [ ]:
# 데이터를 읽으면서 탭을 기준으로 분리하여 데이터 프레임으로 만들기
t_df = pd.read_csv(titanic_data, sep='\t')
t_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# 4. 판다스 데이터 처리

### 4-1. 데이터 구조 및 구성 확인

In [ ]:
# 앞부분 확인
t_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# 뒷부분 확인
t_df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [ ]:
# 데이터 개수/형태 확인
t_df.shape

(156, 12)

In [ ]:
#데이터의 기본 통계치 보기
t_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  156 non-null    int64
 1   Survived     156 non-null    int64
 2   Pclass       156 non-null    int64
 3   Name         156 non-null    str
 4   Sex          156 non-null    str
 5   Age          126 non-null    float64
 6   SibSp        156 non-null    int64
 7   Parch        156 non-null    int64
 8   Ticket       156 non-null    str
 9   Fare         156 non-null    float64
 10  Cabin        31 non-null     str
 11  Embarked     155 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 14.8 KB

In [ ]:
# 데이터 구성 정보 확인하기
t_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,156.000000,156.000000,156.000000,126.000000,156.000000,156.000000,156.000000
mean,78.500000,0.346154,2.423077,28.141508,0.615385,0.397436,28.109587
std,45.177428,0.477275,0.795459,14.613880,1.056235,0.870146,39.401047
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000
25%,39.750000,0.000000,2.000000,19.000000,0.000000,0.000000,8.003150
50%,78.500000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200
75%,117.250000,1.000000,3.000000,35.000000,1.000000,0.000000,30.371850
max,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000

In [ ]:
# 타이타닉 데이터 구조 및 구성 확인하기

sample_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      str
 1   Age     5 non-null      float64
 2   Gender  7 non-null      str
 3   City    6 non-null      str
dtypes: float64(1), str(3)
memory usage: 356.0 bytes

### 4-2. 컬럼명과 인덱스 정리

In [ ]:
# 데이터프레임 복사하기 (deep copy)
sample_backup_df = sample_df.copy()
sample_backup_df

      name   age gender         city
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [ ]:
sample_df = sample_df.rename(columns=str.lower)
sample_df

      name   age gender         city
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [ ]:
sample_df = sample_df.rename(columns=str.capitalize)
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [ ]:
# 숙제) 컴럼명의 첫글자는 소문자로, 나머지는 대문자로 수정
sample_df = sample_df.rename(columns=lambda x: x[0].lower() + x[1:].upper())
sample_df

      nAME   aGE gENDER         cITY
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [ ]:
# 열 이름 변경하기 : 모두 소문자로 변경
# new_cols = []
# for col in sample_df.columns:
#     new_cols.append(col.lower())

sample_df.columns = [col.lower() for col in sample_df.columns]
sample_df.columns = new_cols
sample_df

      name   age gender         city
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [ ]:
# index 확인
t_df.index

RangeIndex(start=0, stop=156, step=1)

In [ ]:
t_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# 행 데이터 삭제하기
drop_index = [2, 4, 152, 154]
t_df = t_df.drop(drop_index, axis=0)
t_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S

In [ ]:
# index를 0부터 순서대로 assign 되도록 reset하기
t_df = t_df.reset_index(drop=True)
t_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
147,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
148,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
149,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [ ]:
t_df = t_df.rename(columns=str.lower)
t_df

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
147,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
148,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
149,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [ ]:
# 컬럼 PassengeId를 index로 설정하기
# t_df.set_index('passengerid')
t_df

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
147,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
148,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
149,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [ ]:
# index를 컬럼으로 만들고, index를 RangeIndex로 reset하기
t_df = t_df.reset_index()
t_df

,index,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,147,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
148,148,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
149,149,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
150,150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
151,151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

### 4-3. 데이터 정렬

In [ ]:
# 'age' 기준으로 정렬
t_df.sort_values(by='age')

,index,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
76,76,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
5,5,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S
14,14,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q
117,117,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,31.2750,NaN,S
41,41,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,107,110,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q
119,119,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
124,124,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
126,126,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
138,138,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C

In [ ]:
# 'age' 기준으로 내림차순으로 정렬
t_df.sort_values(by='age', ascending=False)

,index,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
94,94,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
114,114,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
31,31,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
52,52,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
92,92,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,107,110,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q
119,119,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
124,124,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
126,126,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
138,138,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C

In [ ]:
# 'age', 'pclass'를 기준으로 정렬
t_df.sort_values(by=['pclass', 'age'], ascending=False)

,index,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
114,114,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
92,92,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
130,130,133,0,3,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47.0,1,0,A/5. 3337,14.5000,NaN,S
127,127,130,0,3,"Ekstrom, Mr. Johan",male,45.0,0,0,347061,6.9750,NaN,S
150,150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25,25,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
134,134,137,1,1,"Newsom, Miss. Helen Monypeny",female,19.0,0,2,11752,26.2833,D47,S
29,29,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
53,53,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
62,62,65,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,27.7208,NaN,C

In [ ]:
# 숙제) pclass는 오름차순으로 정렬, age는 내림차순으로 정렬
# 오름차순()
a = t_df.copy()
a = a.sort_values(by=['pclass', 'age'], ascending=[True, False])
a

,index,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
94,94,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
52,52,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
9,9,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
4,4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
122,122,125,0,1,"White, Mr. Percival Wayland",male,54.0,0,1,35281,77.2875,D26,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,107,110,1,3,"Moran, Miss. Bertha",female,NaN,1,0,371110,24.1500,NaN,Q
119,119,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
124,124,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
126,126,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
138,138,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C

In [ ]:
# index를 기준으로 정렬
t_df = t_df.sort_index()
t_df

,index,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,147,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
148,148,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
149,149,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
150,150,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
151,151,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

### 4-4. 데이터 접근/추출
* 범위 지정 : 직접 지정, 인덱서 이용
* 조건 지정

In [ ]:
score_dict={'이름': ['정약용', '이순신', '이율곡', '홍길동'],
            '국어' : [70, 100, 90, 85],
            '영어' : [80, 80, 95, 100],
            '수학' : [100, 70, 90, 90]}
score_df = pd.DataFrame(score_dict)
score_df

    이름   국어   영어   수학
0  정약용   70   80  100
1  이순신  100   80   70
2  이율곡   90   95   90
3  홍길동   85  100   90

In [ ]:
# 행 지정 -> 슬라이싱

score_df[2:3]

    이름  국어  영어  수학
2  이율곡  90  95  90

In [ ]:
# 열 접근

score_df['이름']

0    정약용
1    이순신
2    이율곡
3    홍길동
Name: 이름, dtype: str

In [ ]:
score_df.이름

0    정약용
1    이순신
2    이율곡
3    홍길동
Name: 이름, dtype: str

In [ ]:
# 특정 (행,열)의 데이터 접근
score_df[1:2][['이름', '국어']]

    이름   국어
1  이순신  100

In [ ]:
score_df

    이름   국어   영어   수학
0  정약용   70   80  100
1  이순신  100   80   70
2  이율곡   90   95   90
3  홍길동   85  100   90

In [ ]:
# 인덱서 이용 : 레이블(이름) 인덱서 >> loc
# 행 접근
# loc에서 사용하는 인덱싱은 stop값을 포함한다

score_df.loc[1]

이름    이순신
국어    100
영어     80
수학     70
Name: 1, dtype: object

In [ ]:
# 열 접근
score_df.loc[:,['이름', '국어']]

    이름   국어
0  정약용   70
1  이순신  100
2  이율곡   90
3  홍길동   85

In [ ]:
# (행,열) 접근
score_df.loc[:1, '이름':'영어']

    이름   국어  영어
0  정약용   70  80
1  이순신  100  80

In [ ]:
# 인덱서 이용 : 위치(숫자) 인덱서
# 행 접근
score_df.iloc[:1]

    이름  국어  영어   수학
0  정약용  70  80  100

In [ ]:
# 열 접근
score_df.iloc[:,1:3]

    국어   영어
0   70   80
1  100   80
2   90   95
3   85  100

In [ ]:
# (행,열) 접근
score_df.iloc[:2, 1:3]

    국어  영어
0   70  80
1  100  80

In [ ]:
score_df

    이름   국어   영어   수학
0  정약용   70   80  100
1  이순신  100   80   70
2  이율곡   90   95   90
3  홍길동   85  100   90

In [ ]:
# 조건 지정 추출 : Boolean Indexing
# 직접 지정 방식으로 행 추출
score_df[score_df.수학 >= 90]

    이름  국어   영어   수학
0  정약용  70   80  100
2  이율곡  90   95   90
3  홍길동  85  100   90

In [ ]:
score_df[(score_df.국어 >= 90) & (score_df.수학 >= 90)]

    이름  국어  영어  수학
2  이율곡  90  95  90

In [ ]:
score_df[score_df.이름.isin(['정약용', '이순신'])]

    이름   국어  영어   수학
0  정약용   70  80  100
1  이순신  100  80   70

In [ ]:
# 인덱서 방식으로 행 추출
score_df.loc[score_df.수학 >= 90]

    이름  국어   영어   수학
0  정약용  70   80  100
2  이율곡  90   95   90
3  홍길동  85  100   90

In [ ]:
# (행,열) 데이터 추출
score_df.loc[score_df.수학 >= 90, ['이름', '수학']]

    이름   수학
0  정약용  100
2  이율곡   90
3  홍길동   90

In [ ]:
# 열 데이터에 조건 지정
score_df.loc[:,score_df.columns != "영어"]

    이름   국어   수학
0  정약용   70  100
1  이순신  100   70
2  이율곡   90   90
3  홍길동   85   90

In [ ]:
score_df.loc[:,score_df.dtypes == 'int']

    국어   영어   수학
0   70   80  100
1  100   80   70
2   90   95   90
3   85  100   90

# 타이타닉 데이터 실습하기

In [ ]:
# 타이타닉 데이터 가져오기
titanic_data = 'https://raw.githubusercontent.com/sehakflower/data/main/titanic.csv'
titanic_df = pd.read_csv(titanic_data, sep='\t')

In [ ]:
titanic_df.columns = [col.lower() for col in titanic_df.columns]

In [ ]:
# 171p 데이터 가져오기

# 지정 범위의 행에서 데이터 가져오기
titanic_df[0:5]
titanic_df[0:1]
titanic_df[::3]
titanic_df[::-1]

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S

In [ ]:
# 단순 인덱스로 범위 지정해 데이터 가져오기
titanic_df[::3]

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.00,1,0,A/5 21171,7.2500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.00,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.00,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,NaN,C
12,13,0,3,"Saundercock, Mr. William Henry",male,20.00,0,0,A/5. 2151,8.0500,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.00,0,0,248706,16.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.00,1,0,345763,18.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.00,0,0,248698,13.0000,D56,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,21.0750,NaN,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.00,0,0,PC 17601,27.7208,NaN,C
33,34,0,2,"Wheadon, Mr. Edward H",male,66.00,0,0,C.A. 24579,10.5000,NaN,S
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,2651,11.2417,NaN,C
42,43,0,3,"Kraeff, Mr. Theodor",male,NaN,0,0,349253,7.8958,NaN,C
45,46,0,3,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,8.0500,NaN,S
48,49,0,3,"Samaan, Mr. Youssef",male,NaN,2,0,2662,21.6792,NaN,C
51,52,0,3,"Nosworthy, Mr. Richard Cater",male,21.00,0,0,A/4. 39886,7.8000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.00,0,1,113509,61.9792,B30,C
57,58,0,3,"Novel, Mr. Mansouer",male,28.50,0,0,2697,7.2292,NaN,C
60,61,0,3,"Sirayanian, Mr. Orsen",male,22.00,0,0,2669,7.2292,NaN,C
63,64,0,3,"Skoog, Master. Harald",male,4.00,3,2,347088,27.9000,NaN,S
66,67,1,2,"Nye, Mrs. (Elizabeth Ramell)",female,29.00,0,0,C.A. 29395,10.5000,F33,S
69,70,0,3,"Kink, Mr. Vincenz",male,26.00,2,0,315151,8.6625,NaN,S
72,73,0,2,"Hood, Mr. Ambrose Jr",male,21.00,0,0,S.O.C. 14879,73.5000,NaN,S
75,76,0,3,"Moen, Mr. Sigurd Hansen",male,25.00,0,0,348123,7.6500,F G73,S
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
81,82,1,3,"Sheerlinck, Mr. Jan Baptist",male,29.00,0,0,345779,9.5000,NaN,S
84,85,1,2,"Ilett, Miss. Bertha",female,17.00,0,0,SO/C 14885,10.5000,NaN,S
87,88,0,3,"Slocovski, Mr. Selman Francis",male,NaN,0,0,SOTON/OQ 392086,8.0500,NaN,S
90,91,0,3,"Christmann, Mr. Emil",male,29.00,0,0,343276,8.0500,NaN,S
93,94,0,3,"Dean, Mr. Bertram Frank",male,26.00,1,2,C.A. 2315,20.5750,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.00,0,0,PC 17754,34.6542,A5,C
99,100,0,2,"Kantor, Mr. Sinai",male,34.00,1,0,244367,26.0000,NaN,S
102,103,0,1,"White, Mr. Richard Frasar",male,21.00,0,1,35281,77.2875,D26,S
105,106,0,3,"Mionoff, Mr. Stoytcho",male,28.00,0,0,349207,7.8958,NaN,S
108,109,0,3,"Rekic, Mr. Tido",male,38.00,0,0,349249,7.8958,NaN,S
111,112,0,3,"Zabour, Miss. Hileni",female,14.50,1,0,2665,14.4542,NaN,C
114,115,0,3,"Attalah, Miss. Malake",female,17.00,0,0,2627,14.4583,NaN,C
117,118,0,2,"Turpin, Mr. William John Robert",male,29.00,1,0,11668,21.0000,NaN,S
120,121,0,2,"Hickman, Mr. Stanley George",male,21.00,2,0,S.O.C. 14879,73.5000,NaN,S
123,124,1,2,"Webber, Miss. Susan",female,32.50,0,0,27267,13.0000,E101,S
126,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
129,130,0,3,"Ekstrom, Mr. Johan",male,45.00,0,0,347061,6.9750,NaN,S
132,133,0,3,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47.00,1,0,A/5. 3337,14.5000,NaN,S
135,136,0,2,"Richard, Mr. Emile",male,23.00,0,0,SC/PARIS 2133,15.0458,NaN,C
138,139,0,3,"Osen, Mr. Olaf Elon",male,16.00,0,0,7534,9.2167,NaN,S
141,142,1,3,"Nysten, Miss. Anna Sofia",female,22.00,0,0,347081,7.7500,NaN,S
144,145,0,2,"Andrew, Mr. Edgardo Samuel",male,18.00,0,0,231945,11.5000,NaN,S
147,148,0,3,"Ford, Miss. Robina Maggie ""Ruby""",female,9.00,2,2,W./C. 6608,34.3750,NaN,S
150,151,0,2,"Bateman, Rev. Robert James",male,51.00,0,0,S.O.P. 1166,12.5250,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.50,0,2,A/5. 851,14.5000,NaN,S

In [ ]:
# 지정 범위의 열에서 데이터 가져오기

len(titanic_df.columns)

12

In [ ]:
titanic_df[titanic_df.columns[0]]

0        1
1        2
2        3
3        4
4        5
      ...
151    152
152    153
153    154
154    155
155    156
Name: PassengerId, Length: 156, dtype: int64

In [ ]:
titanic_df[titanic_df.columns[11]]

0      S
1      C
2      S
3      S
4      S
      ..
151    S
152    S
153    S
154    S
155    C
Name: Embarked, Length: 156, dtype: str

In [ ]:
# 열 이름으로 데이터 가져오기

age = titanic_df['age']
print(type(age))

<class 'pandas.Series'>

In [ ]:
titanic_df['age']
titanic_df.age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
151    22.0
152    55.5
153    40.5
154     NaN
155    51.0
Name: age, Length: 156, dtype: float64

In [ ]:
# 열 이름과 위치를 이용해 데이터 가져오기

print(titanic_df[titanic_df.columns[0]][0])
print(titanic_df['age'][0])
print(titanic_df[titanic_df.columns[0]][2])
print(titanic_df[titanic_df.columns[-1]][0])
type(titanic_df[titanic_df.columns[0]][0])

1
22.0
3
S

numpy.int64

In [ ]:
titanic_df[titanic_df.columns[0]][2:6]
titanic_df[titanic_df.columns[0]][:-1]
titanic_df[titanic_df.columns[0]][::3]
titanic_df[titanic_df.columns[0]][-1:]
titanic_df[titanic_df.columns[0]][::-1]

155    156
154    155
153    154
152    153
151    152
      ...
4        5
3        4
2        3
1        2
0        1
Name: passengerid, Length: 156, dtype: int64

In [ ]:
titanic_df[['pclass', 'name', 'sex']]
titanic_df[[titanic_df.columns[2], titanic_df.columns[3],titanic_df.columns[4]]]

     pclass                                               name     sex
0         3                            Braund, Mr. Owen Harris    male
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2         3                             Heikkinen, Miss. Laina  female
3         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4         3                           Allen, Mr. William Henry    male
..      ...                                                ...     ...
151       1                  Pears, Mrs. Thomas (Edith Wearne)  female
152       3                                   Meo, Mr. Alfonzo    male
153       3                    van Billiard, Mr. Austin Blyler    male
154       3                              Olsen, Mr. Ole Martin    male
155       1                        Williams, Mr. Charles Duane    male

[156 rows x 3 columns]

In [ ]:
titanic_df[[titanic_df.columns[2], titanic_df.columns[3], titanic_df.columns[4]]][2:15:3]

    pclass                                               name     sex
2        3                             Heikkinen, Miss. Laina  female
5        3                                   Moran, Mr. James    male
8        3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female
11       1                           Bonnell, Miss. Elizabeth  female
14       3               Vestrom, Miss. Hulda Amanda Adolfina  female

In [ ]:
print(titanic_df[titanic_df.columns[0]][0])
print(titanic_df[titanic_df.columns[0]][2])
# print(titanic_df[columns[0]][-1]) # 실행시 오류 발생 : name 'columns' is not defined
type(titanic_df[titanic_df.columns[0]][0])

1
3

numpy.int64

In [ ]:
# 인덱스 이름을 기준으로 데이터 가져오기 : loc 속성
titanic_df.loc[0]

passengerid                          1
survived                             0
pclass                               3
name           Braund, Mr. Owen Harris
sex                               male
age                               22.0
sibsp                                1
parch                                0
ticket                       A/5 21171
fare                              7.25
cabin                              NaN
embarked                             S
Name: 0, dtype: object

In [ ]:
# loc속성은 끝 인덱스까지 표시된다 > 0에서부터 5번 인덱스까지 표시

titanic_df.loc[0:5]

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

In [ ]:
# 0번 인덱스부터 10번 인덱스까지 2씩 건너뛰면서 출력

titanic_df.loc[0:10:2]

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S

In [ ]:
# 0번부터 마지막 인덱스까지 age열의 모든 행을 가져오기

titanic_df.loc[:, 'age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
151    22.0
152    55.5
153    40.5
154     NaN
155    51.0
Name: age, Length: 156, dtype: float64

In [ ]:
# 0번부터 마지막 인덱스까지 age, sex열의 모든 데이터를 가져오기
titanic_df.loc[:, ['age', 'sex']]

      age     sex
0    22.0    male
1    38.0  female
2    26.0  female
3    35.0  female
4    35.0    male
..    ...     ...
151  22.0  female
152  55.5    male
153  40.5    male
154   NaN    male
155  51.0    male

[156 rows x 2 columns]

In [ ]:
# 3번부터 7번 인덱스까지 데이터 중 age와 sex열만 가져오기
titanic_df.loc[3:7, ['age', 'sex']]

    age     sex
3  35.0  female
4  35.0    male
5   NaN    male
6  54.0    male
7   2.0    male

In [ ]:
# 2번부터 5번 인덱스까지 survived열부터 age열까지

titanic_df.loc[2:5, 'survived':'age']

,survived,pclass,name,sex,age
2,1,3,"Heikkinen, Miss. Laina",female,26.0
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0
4,0,3,"Allen, Mr. William Henry",male,35.0
5,0,3,"Moran, Mr. James",male,NaN

In [ ]:
# 인덱스 순서를 기준으로 데이터 가져오기 : iloc 속성

titanic_df.iloc[0]

passengerid                          1
survived                             0
pclass                               3
name           Braund, Mr. Owen Harris
sex                               male
age                               22.0
sibsp                                1
parch                                0
ticket                       A/5 21171
fare                              7.25
cabin                              NaN
embarked                             S
Name: 0, dtype: object

In [ ]:
# 0부터 4행까지 데이터가 표시된다

titanic_df.iloc[0:5]

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# 0행에서부터 9행까지 3씩 건너뛰면서

titanic_df.iloc[0:10:3]

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [ ]:
# 0행에서부터 마지막 행까지 0열과 2열(=세번째 열) 가져오기 (범위가 아님에 주의 !!!)

titanic_df.iloc[:, [0,2]]

     passengerid  pclass
0              1       3
1              2       1
2              3       3
3              4       1
4              5       3
..           ...     ...
151          152       1
152          153       3
153          154       3
154          155       3
155          156       1

[156 rows x 2 columns]

In [ ]:
# 1번째 행부터 4번째 행까지 1열부터 3열까지 가져오기
titanic_df.iloc[1:5, 1:4]

   survived  pclass                                               name
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         1       3                             Heikkinen, Miss. Laina
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4         0       3                           Allen, Mr. William Henry

## 4-5. 그룹별로 요약하여 데이터 확인
* value_counts()
* groupby()
* pivot_table()

In [ ]:
sample_file = 'data/sales_sample.csv'

In [ ]:
# 샘플 파일 로딩
import pandas as pd
sales_df = pd.read_csv(sample_file)
sales_df

    지역   상품  판매수량   매출
0   서울  노트북     2  120
1   서울  태블릿     1   80
2   부산  노트북     2  100
3   부산  태블릿     1   70
4   서울  노트북     3  150
5   부산  노트북     1  110
6   대전  노트북     2  130
7   대전  태블릿     2   90
8   서울  태블릿     2  160
9   부산  태블릿     3  210
10  대전  노트북     1   65
11  대전  태블릿     1   45
12  서울  노트북     1   60
13  부산  노트북     3  150
14  대전  노트북     2  120
15  서울  태블릿     2  160
16  부산  태블릿     1   70
17  대전  태블릿     3  135
18  서울  노트북     2  120
19  부산  태블릿     2  140

In [ ]:
# 지역별 판매 기록의 개수(매출이 아니라 '건'수!!)

sales_df['지역'].value_counts()

지역
서울    7
부산    7
대전    6
Name: count, dtype: int64

In [ ]:
# 상품별 판매 기록의 개수와 비율

sales_df['상품'].value_counts()

상품
노트북    10
태블릿    10
Name: count, dtype: int64

In [ ]:
# 데이터의 비율 확인
sales_df['상품'].value_counts(normalize=True)

상품
노트북    0.5
태블릿    0.5
Name: proportion, dtype: float64

In [ ]:
# 지역과 상품의 조합별 판매 기록 개수 ()

sales_df.value_counts(['지역','상품'])

지역  상품
서울  노트북    4
부산  태블릿    4
서울  태블릿    3
부산  노트북    3
대전  노트북    3
    태블릿    3
Name: count, dtype: int64

In [43]:
import pandas as pd

sample_df = pd.read_csv('data/sample_data.csv')
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [ ]:
sample_df['City'].value_counts()

City
New York       2
Houston        2
Los Angeles    1
Chicago        1
Name: count, dtype: int64

In [ ]:
# 지역별 총매출

sales_df.groupby(by='지역')['매출'].sum()

지역
대전    585
부산    850
서울    850
Name: 매출, dtype: int64

In [ ]:
# 상품별 평균 매출 > 상품을 기준으로 매출의 평균 계산

sales_df.groupby(by='상품')['매출'].mean()

상품
노트북    112.5
태블릿    116.0
Name: 매출, dtype: float64

In [ ]:
# 지역별 판매수량의 합계와 매출의 합계 > 지역을 기준으로 판매수량과 매출의 각각 합계 구하기

sales_df.groupby(by='지역')[['판매수량', '매출']].sum()

    판매수량   매출
지역
대전    11  585
부산    13  850
서울    13  850

In [ ]:
# 지역과 상품별 평균 매출

sales_df.groupby(by=['지역', '상품'])['매출'].mean()

지역  상품
대전  노트북    105.000000
    태블릿     90.000000
부산  노트북    120.000000
    태블릿    122.500000
서울  노트북    112.500000
    태블릿    133.333333
Name: 매출, dtype: float64

In [ ]:
# 위의 실습을 pivot_table()로 적용

sales_df.pivot_table(
    values='매출',
    aggfunc='mean',
    index='지역',
    columns='상품'
)

상품    노트북         태블릿
지역
대전  105.0   90.000000
부산  120.0  122.500000
서울  112.5  133.333333

In [ ]:
# 지역별·상품별 총매출을 구하고 행과 열의 합계 표시

sales_df.pivot_table(
    index='상품',
    columns='지역',
    values='매출',
    aggfunc='sum',
    margins=True    # 전체를 통합한 것
)

지역    대전   부산   서울   All
상품
노트북  315  360  450  1125
태블릿  270  490  400  1160
All  585  850  850  2285

In [ ]:
# 지역별 매출 : 건수, 합계, 평균, 최대값을 한번에 출력

sales_df.groupby(by='지역')['매출'].agg(['count', 'sum', 'mean', 'max'])

    count  sum        mean  max
지역
대전      6  585   97.500000  135
부산      7  850  121.428571  210
서울      7  850  121.428571  160

## 5-1. 결측치 처리

In [45]:
import pandas as pd
sample_df = pd.read_csv('./data/sample_data.csv')
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [6]:
sample_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      str
 1   Age     5 non-null      float64
 2   Gender  7 non-null      str
 3   City    6 non-null      str
dtypes: float64(1), str(3)
memory usage: 356.0 bytes

In [7]:
sample_df.isna().sum()

Name      0
Age       2
Gender    0
City      1
dtype: int64

In [15]:
sample_df.isnull()

    Name    Age  Gender   City
0  False  False   False  False
1  False   True   False  False
2  False  False   False   True
3  False  False   False  False
4  False   True   False  False
5  False  False   False  False
6  False  False   False  False

In [16]:
sample_df.isnull().sum()

Name      0
Age       2
Gender    0
City      1
dtype: int64

In [14]:
# 결측치가 있는 데이터 확인
# 'Age' 컬럼에 결측치가 있는지와 결측치 데이터 확인

print(sample_df['Age'].isna().sum())
sample_df[sample_df['Age'].isna()]

2

     Name  Age Gender         City
1     Bob  NaN      M  Los Angeles
4  Edward  NaN      M      Houston

In [26]:
# 어떤 컬럼에든 결측치가 있는 데이터의 개수, 데이터 확인 (결측치가 몇개인지 count)

# 행방향
sample_df.isna().any()
# 열방향
na_df = sample_df[sample_df.isna().any(axis=1)]
print(len(na_df))
na_df

3

      Name   Age Gender         City
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
4   Edward   NaN      M      Houston

In [31]:
# 결측치가 있는 데이터를 삭제 : dropna()

sample_df.dropna() # 결측치가 있는 모든 행을 삭제해버림

# City에 결측치가 있는 경우 데이터 삭제
sample_df = sample_df.dropna(subset='City')

sample_df.dropna(subset=['Age','City'])

    Name   Age Gender      City
0  Alice  24.0      F  New York
3  David  29.0      M   Chicago
5  Alice  24.0      F  New York
6  Susan  32.0      F   Houston

In [44]:
# Age 결측치는 Age의 평균값으로 채우기
age_avg = sample_df['Age'].mean()
print(age_avg)

sample_df['Age'] = sample_df['Age'].fillna(sample_df['Age'].mean())
sample_df

26.2

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob  26.2      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward  26.2      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

In [46]:
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

## 5-2. 중복치 처리

In [54]:
# 중복값 확인
sample_df.duplicated(keep=False).sum()

np.int64(2)

In [56]:
# 불리언 인덱싱 적용하여 중복행 모두 출력

sample_df[sample_df.duplicated(keep=False)]

    Name   Age Gender      City
0  Alice  24.0      F  New York
5  Alice  24.0      F  New York

In [58]:
# 중복값 삭제

# 전체가 중복일때 사용한다 > 중복인 값 자동으로 삭제하고 하나만 남김
sample_df.drop_duplicates()

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
6    Susan  32.0      F      Houston

In [59]:
sample_df = sample_df.drop_duplicates()
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
6    Susan  32.0      F      Houston